default: &default
  adapter: sqlite3
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: myproject_development

test:
  <<: *default
  database: myproject_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: SmartMenu_production
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock  